version: 1
formatters:
  default_console_process:
    format: '%(asctime)s %(levelname)s %(message)s'
    datefmt: '%d-%m-%y %H:%M:%S'
  extended_console_process:
    format: '%(asctime)s %(module)s %(funcName)s %(levelname)s %(message)s'
    datefmt: '%d-%m-%y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default_console_process
    stream: ext://sys.stderr
loggers:
  custom:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
