version: 1
formatters:
  default_console_process:
    format: '%(asctime)s %(levelname)s %(message)s'
    datefmt: '%d-%m-%y %H:%M:%S'
  extended_console_process:
    format: '%(asctime)s %(module)s %(funcName)s %(levelname)s %(message)s'
    datefmt: '%d-%m-%y %H:%M:%S'
handlers:
  full_file_handler:
    class: logging.FileHandler
    filename: run.log
    level: DEBUG
    formatter: extended_console_process
  stream_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: default_console_process
    stream: ext://sys.stderr
loggers:
  custom:
    level: DEBUG
    handlers: [full_file_handler]
    propagate: yes
root:
  level: DEBUG
  handlers: [full_file_handler, stream_handler]
